# Generated by Django 4.2 on 2023-10-10 05:40

from django.db import migrations, models
import job.images_urls


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, max_length=90000, null=True, upload_to=job.images_urls.get_job),
        ),
    ]
